language: c
sudo: false
os:
#  - osx
  - linux
env:
  - LIBMILL="git://github.com/sustrik/libmill.git"
branches:
  only:
    - master

before_install:
  - git clone $LIBMILL
  - cd libmill

install:
  - ./autogen.sh
  - ./configure
  - make

script:
  - make check

after_failure:
  - cat libmill/test-suite.log

notifications:
  email: false
