language: c

sudo: false

os:
  - osx
  - linux

branches:
  only:
    - master

install:
  - ./autogen.sh
  - ./configure
  - make

script:
  - make check

after_failure:
  - for f in tests/*.log; do echo; echo "${f}:"; cat $f; done;

notifications:
  email: false
