language: c

sudo: false

os:
  - osx
  - linux

compiler:
  - gcc
  - clang

env:
  matrix:
   - CONF="autotools-shared"
   - CONF="autotools-static"
   - CONF="cmake-shared"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - clang

branches:
  only:
    - master

install:
  - if [[ $CONF == "autotools-shared" ]]; then ./autogen.sh && ./configure && make; fi
  - if [[ $CONF == "autotools-statis" ]]; then ./autogen.sh && ./configure --disable-shared && make; fi
  - if [[ $CONF == "cmake-shared"  ]]; then cmake . && make; fi

script:
  - if [[ $CMAKE == "false" ]]; then make check; else make test; fi

after_failure:
  - for f in tests/*.log; do echo; echo "${f}:"; cat $f; done;
  - cat test-suite.log

notifications:
  email: false
